# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoo_TutorialWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StepByStepTutorial(object):
    def setupUi(self, StepByStepTutorial):
        StepByStepTutorial.setObjectName("StepByStepTutorial")
        StepByStepTutorial.resize(800, 900)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(StepByStepTutorial)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.title_ = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_.setFont(font)
        self.title_.setAlignment(QtCore.Qt.AlignCenter)
        self.title_.setObjectName("title_")
        self.verticalLayout_7.addWidget(self.title_)
        self.line_7 = QtWidgets.QFrame(StepByStepTutorial)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.label = QtWidgets.QLabel(StepByStepTutorial)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_4 = QtWidgets.QFrame(StepByStepTutorial)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_ICsLoaded = QtWidgets.QCheckBox(StepByStepTutorial)
        self.checkBox_ICsLoaded.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ICsLoaded.sizePolicy().hasHeightForWidth())
        self.checkBox_ICsLoaded.setSizePolicy(sizePolicy)
        self.checkBox_ICsLoaded.setText("")
        self.checkBox_ICsLoaded.setCheckable(True)
        self.checkBox_ICsLoaded.setChecked(False)
        self.checkBox_ICsLoaded.setObjectName("checkBox_ICsLoaded")
        self.horizontalLayout.addWidget(self.checkBox_ICsLoaded)
        self.label_ICAstep_title = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ICAstep_title.setFont(font)
        self.label_ICAstep_title.setObjectName("label_ICAstep_title")
        self.horizontalLayout.addWidget(self.label_ICAstep_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_ICAstep_details = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ICAstep_details.setFont(font)
        self.label_ICAstep_details.setTextFormat(QtCore.Qt.AutoText)
        self.label_ICAstep_details.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ICAstep_details.setWordWrap(True)
        self.label_ICAstep_details.setIndent(20)
        self.label_ICAstep_details.setObjectName("label_ICAstep_details")
        self.verticalLayout_2.addWidget(self.label_ICAstep_details)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(StepByStepTutorial)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_ICNsLoaded = QtWidgets.QCheckBox(StepByStepTutorial)
        self.checkBox_ICNsLoaded.setEnabled(False)
        self.checkBox_ICNsLoaded.setText("")
        self.checkBox_ICNsLoaded.setObjectName("checkBox_ICNsLoaded")
        self.horizontalLayout_2.addWidget(self.checkBox_ICNsLoaded)
        self.label_ICNstep_title = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ICNstep_title.setFont(font)
        self.label_ICNstep_title.setObjectName("label_ICNstep_title")
        self.horizontalLayout_2.addWidget(self.label_ICNstep_title)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_ICNstep_details = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ICNstep_details.setFont(font)
        self.label_ICNstep_details.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ICNstep_details.setWordWrap(True)
        self.label_ICNstep_details.setIndent(20)
        self.label_ICNstep_details.setObjectName("label_ICNstep_details")
        self.verticalLayout_3.addWidget(self.label_ICNstep_details)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(StepByStepTutorial)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_ClassificationsPresent = QtWidgets.QCheckBox(StepByStepTutorial)
        self.checkBox_ClassificationsPresent.setEnabled(False)
        self.checkBox_ClassificationsPresent.setText("")
        self.checkBox_ClassificationsPresent.setObjectName("checkBox_ClassificationsPresent")
        self.horizontalLayout_3.addWidget(self.checkBox_ClassificationsPresent)
        self.label_Mapstep_title = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Mapstep_title.setFont(font)
        self.label_Mapstep_title.setObjectName("label_Mapstep_title")
        self.horizontalLayout_3.addWidget(self.label_Mapstep_title)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_Mapstep_details = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Mapstep_details.setFont(font)
        self.label_Mapstep_details.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Mapstep_details.setWordWrap(True)
        self.label_Mapstep_details.setIndent(20)
        self.label_Mapstep_details.setObjectName("label_Mapstep_details")
        self.verticalLayout_4.addWidget(self.label_Mapstep_details)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.line_3 = QtWidgets.QFrame(StepByStepTutorial)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_OutputGenerated = QtWidgets.QCheckBox(StepByStepTutorial)
        self.checkBox_OutputGenerated.setEnabled(False)
        self.checkBox_OutputGenerated.setText("")
        self.checkBox_OutputGenerated.setObjectName("checkBox_OutputGenerated")
        self.horizontalLayout_4.addWidget(self.checkBox_OutputGenerated)
        self.label_Output_title = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Output_title.setFont(font)
        self.label_Output_title.setObjectName("label_Output_title")
        self.horizontalLayout_4.addWidget(self.label_Output_title)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.label_Output_details = QtWidgets.QLabel(StepByStepTutorial)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Output_details.setFont(font)
        self.label_Output_details.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Output_details.setWordWrap(True)
        self.label_Output_details.setIndent(20)
        self.label_Output_details.setObjectName("label_Output_details")
        self.verticalLayout_6.addWidget(self.label_Output_details)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.buttonBox = QtWidgets.QDialogButtonBox(StepByStepTutorial)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_6.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout)

        self.retranslateUi(StepByStepTutorial)
        QtCore.QMetaObject.connectSlotsByName(StepByStepTutorial)

    def retranslateUi(self, StepByStepTutorial):
        _translate = QtCore.QCoreApplication.translate
        StepByStepTutorial.setWindowTitle(_translate("StepByStepTutorial", "Step-by-Step tutorial & tips"))
        self.title_.setText(_translate("StepByStepTutorial", "Analysis\' Tutorial: Steps Completed & Suggestions"))
        self.label.setText(_translate("StepByStepTutorial", "Next step unchecked & bolded; previously completed steps checked & greyed out. Contents are updated based on state of current analysis, return as needed for suggestions"))
        self.label_ICAstep_title.setText(_translate("StepByStepTutorial", "1a. Load ICA components"))
        self.label_ICAstep_details.setText(_translate("StepByStepTutorial", "-Click on \"Load ICA components\" or select from under \"Networks\" menu"))
        self.label_ICNstep_title.setText(_translate("StepByStepTutorial", "1b. Load ICN templates"))
        self.label_ICNstep_details.setText(_translate("StepByStepTutorial", "-Click on \"Load ICN templates\" or select from under \"Networks\" menu"))
        self.label_Mapstep_title.setText(_translate("StepByStepTutorial", "2. Classify ICA components using ICN templates"))
        self.label_Mapstep_details.setText(_translate("StepByStepTutorial", "<html><head/><body><p>-Load ICA components (step 1a) &amp; templates (step 1b)</p></body></html>"))
        self.label_Output_title.setText(_translate("StepByStepTutorial", "3. Create figures, tables and masks"))
        self.label_Output_details.setText(_translate("StepByStepTutorial", "<html><head/><body><p>-Create one or more ICA &gt; ICN mapping(s) in step 2</p></body></html>"))

