# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoo_PreferrencesWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 701)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 650, 651, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(10, 510, 651, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(3)
        self.frame_4.setObjectName("frame_4")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 651, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-10, 40, 651, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_RestoreDefaults = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_RestoreDefaults.setObjectName("pushButton_RestoreDefaults")
        self.horizontalLayout.addWidget(self.pushButton_RestoreDefaults)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(60, 600, 541, 51))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 651, 201))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 20, 541, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_LoadICAonStartup = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_LoadICAonStartup.setFont(font)
        self.checkBox_LoadICAonStartup.setObjectName("checkBox_LoadICAonStartup")
        self.verticalLayout_2.addWidget(self.checkBox_LoadICAonStartup)
        self.checkBox_LoadICNonStartup = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_LoadICNonStartup.setFont(font)
        self.checkBox_LoadICNonStartup.setChecked(True)
        self.checkBox_LoadICNonStartup.setObjectName("checkBox_LoadICNonStartup")
        self.verticalLayout_2.addWidget(self.checkBox_LoadICNonStartup)
        self.checkBox_LoadNoiseOnStartup = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_LoadNoiseOnStartup.setFont(font)
        self.checkBox_LoadNoiseOnStartup.setObjectName("checkBox_LoadNoiseOnStartup")
        self.verticalLayout_2.addWidget(self.checkBox_LoadNoiseOnStartup)
        self.checkBox_LoadAnatonStartup = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_LoadAnatonStartup.setFont(font)
        self.checkBox_LoadAnatonStartup.setChecked(True)
        self.checkBox_LoadAnatonStartup.setObjectName("checkBox_LoadAnatonStartup")
        self.verticalLayout_2.addWidget(self.checkBox_LoadAnatonStartup)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(550, 30, 101, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 651, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 651, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_CorrelateOnClick = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CorrelateOnClick.setFont(font)
        self.checkBox_CorrelateOnClick.setChecked(True)
        self.checkBox_CorrelateOnClick.setObjectName("checkBox_CorrelateOnClick")
        self.gridLayout.addWidget(self.checkBox_CorrelateOnClick, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.checkBox_AllowICAmultiClass = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_AllowICAmultiClass.setFont(font)
        self.checkBox_AllowICAmultiClass.setObjectName("checkBox_AllowICAmultiClass")
        self.gridLayout.addWidget(self.checkBox_AllowICAmultiClass, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 400, 651, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 491, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferrences"))
        self.label_7.setText(_translate("Dialog", "Any of the above customizations, saved during the current or a previous session, can always be undone:"))
        self.pushButton_RestoreDefaults.setText(_translate("Dialog", "Reset All Settings"))
        self.label_8.setText(_translate("Dialog", "Once the above defaults have been finalized, either \'Save All\' for use in future sessions, or \'Cancel\' to discard & return to main session:"))
        self.groupBox.setTitle(_translate("Dialog", "Load/Change default directories && file(s):"))
        self.checkBox_LoadICAonStartup.setText(_translate("Dialog", "Load default ICA components on startup"))
        self.checkBox_LoadICNonStartup.setText(_translate("Dialog", "Load default ICN templates on startup"))
        self.checkBox_LoadNoiseOnStartup.setText(_translate("Dialog", "Load default Noise templates on startup"))
        self.checkBox_LoadAnatonStartup.setText(_translate("Dialog", "Load default anatomical/structure MRI on startup"))
        self.label.setText(_translate("Dialog", "To change any setting, toggle the checkbox OFF then ON"))
        self.groupBox_2.setTitle(_translate("Dialog", "Application behavior settings:"))
        self.checkBox_CorrelateOnClick.setText(_translate("Dialog", "Correlate ICA && ICN pairs when clicked"))
        self.label_3.setText(_translate("Dialog", "By default, new pairs of items are correlated when they are clicked on. Turning off this option may speed up GUI"))
        self.checkBox_AllowICAmultiClass.setText(_translate("Dialog", "Allow ICA multiclassifications"))
        self.label_4.setText(_translate("Dialog", "If checked, ICA comps. will remain in ICA list widget once classified, allowing for additional ICA > ICN classifications"))
        self.groupBox_3.setTitle(_translate("Dialog", "Display && Output defaults:"))
        self.label_2.setText(_translate("Dialog", "To set or changing default display plotting options, or output options for figures, tables & masks, see \'Display Options\' and \'Output Options\' under the \'Edit\' menu"))

