# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoo_OutputOptionsWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(667, 578)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 530, 641, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 230, 641, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 451, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_ThreshICApercentile = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ThreshICApercentile.setFont(font)
        self.checkBox_ThreshICApercentile.setChecked(True)
        self.checkBox_ThreshICApercentile.setObjectName("checkBox_ThreshICApercentile")
        self.horizontalLayout.addWidget(self.checkBox_ThreshICApercentile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.doubleSpinBox_ThreshPercentile = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_ThreshPercentile.setFont(font)
        self.doubleSpinBox_ThreshPercentile.setMaximum(100.0)
        self.doubleSpinBox_ThreshPercentile.setSingleStep(0.5)
        self.doubleSpinBox_ThreshPercentile.setProperty("value", 99.0)
        self.doubleSpinBox_ThreshPercentile.setObjectName("doubleSpinBox_ThreshPercentile")
        self.horizontalLayout.addWidget(self.doubleSpinBox_ThreshPercentile)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_ThreshICAfractionOfMax = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ThreshICAfractionOfMax.setFont(font)
        self.checkBox_ThreshICAfractionOfMax.setChecked(True)
        self.checkBox_ThreshICAfractionOfMax.setObjectName("checkBox_ThreshICAfractionOfMax")
        self.horizontalLayout_3.addWidget(self.checkBox_ThreshICAfractionOfMax)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.doubleSpinBox_ThreshFractionMax = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_ThreshFractionMax.setFont(font)
        self.doubleSpinBox_ThreshFractionMax.setMaximum(1.0)
        self.doubleSpinBox_ThreshFractionMax.setSingleStep(0.03)
        self.doubleSpinBox_ThreshFractionMax.setProperty("value", 0.33)
        self.doubleSpinBox_ThreshFractionMax.setObjectName("doubleSpinBox_ThreshFractionMax")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_ThreshFractionMax)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.checkBox_SmoothEdges = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SmoothEdges.setFont(font)
        self.checkBox_SmoothEdges.setChecked(True)
        self.checkBox_SmoothEdges.setObjectName("checkBox_SmoothEdges")
        self.verticalLayout.addWidget(self.checkBox_SmoothEdges)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(498, 29, 131, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 430, 641, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_SaveOutputOptions = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_SaveOutputOptions.setGeometry(QtCore.QRect(10, 30, 151, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_SaveOutputOptions.setFont(font)
        self.pushButton_SaveOutputOptions.setObjectName("pushButton_SaveOutputOptions")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(178, 24, 441, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 641, 171))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 19, 465, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.spinBox_FigCols = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_FigCols.setFont(font)
        self.spinBox_FigCols.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_FigCols.setMinimum(1)
        self.spinBox_FigCols.setMaximum(99)
        self.spinBox_FigCols.setProperty("value", 3)
        self.spinBox_FigCols.setObjectName("spinBox_FigCols")
        self.gridLayout.addWidget(self.spinBox_FigCols, 1, 2, 1, 1)
        self.spinBox_FigRows = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_FigRows.setFont(font)
        self.spinBox_FigRows.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_FigRows.setMinimum(1)
        self.spinBox_FigRows.setMaximum(99)
        self.spinBox_FigRows.setProperty("value", 10)
        self.spinBox_FigRows.setObjectName("spinBox_FigRows")
        self.gridLayout.addWidget(self.spinBox_FigRows, 1, 1, 1, 1)
        self.checkBox_CreateFigure = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CreateFigure.setFont(font)
        self.checkBox_CreateFigure.setChecked(True)
        self.checkBox_CreateFigure.setObjectName("checkBox_CreateFigure")
        self.gridLayout.addWidget(self.checkBox_CreateFigure, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.checkBox_ConcatVertical = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ConcatVertical.setFont(font)
        self.checkBox_ConcatVertical.setChecked(True)
        self.checkBox_ConcatVertical.setObjectName("checkBox_ConcatVertical")
        self.horizontalLayout_2.addWidget(self.checkBox_ConcatVertical)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.checkBox_CreateTable = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_CreateTable.setFont(font)
        self.checkBox_CreateTable.setChecked(True)
        self.checkBox_CreateTable.setObjectName("checkBox_CreateTable")
        self.verticalLayout_2.addWidget(self.checkBox_CreateTable)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(470, 24, 151, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(460, 120, 181, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Output Options"))
        self.groupBox.setTitle(_translate("Dialog", "Mask creation options:"))
        self.checkBox_ThreshICApercentile.setText(_translate("Dialog", "Threshold ICA vol. by percentile:"))
        self.checkBox_ThreshICAfractionOfMax.setText(_translate("Dialog", "Threshold ICA vol. by fraction of |max value|:"))
        self.checkBox_SmoothEdges.setText(_translate("Dialog", "Smooth edges of mask"))
        self.label.setText(_translate("Dialog", "Masks are created by thresholding classified ICA comp. vols., then labelled with the ICN template name"))
        self.groupBox_5.setTitle(_translate("Dialog", "Save current output creation settings as Network Zoo defaults:"))
        self.pushButton_SaveOutputOptions.setText(_translate("Dialog", "Save output settings"))
        self.label_2.setText(_translate("Dialog", "By default, current output creation settings are discarded once Network Zoo closes. Saving current settings will set these options as the default for future use"))
        self.groupBox_2.setTitle(_translate("Dialog", "Figure && Table creation options:"))
        self.label_3.setText(_translate("Dialog", "max. rows:     "))
        self.label_4.setText(_translate("Dialog", "max. columns:"))
        self.checkBox_CreateFigure.setText(_translate("Dialog", "Create concatenated figure(s) of displays"))
        self.checkBox_ConcatVertical.setText(_translate("Dialog", "Concat displays vertically"))
        self.checkBox_CreateTable.setText(_translate("Dialog", "Create table of current classifications"))
        self.label_5.setText(_translate("Dialog", "Figure(s) show spatial maps & time/freq. plots for all current ICA > ICN classifications, using display settings"))
        self.label_6.setText(_translate("Dialog", "Table includes ICA comp. names, template names, etc., saved as .csv file"))

