# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoo_PreferrencesWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(668, 588)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 540, 651, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 651, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(7)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 651, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_LoadICAonStartup = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_LoadICAonStartup.setObjectName("checkBox_LoadICAonStartup")
        self.verticalLayout.addWidget(self.checkBox_LoadICAonStartup)
        self.checkBox_LoadICNonStartup = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_LoadICNonStartup.setChecked(True)
        self.checkBox_LoadICNonStartup.setObjectName("checkBox_LoadICNonStartup")
        self.verticalLayout.addWidget(self.checkBox_LoadICNonStartup)
        self.checkBox_LoadNoiseOnStartup = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_LoadNoiseOnStartup.setObjectName("checkBox_LoadNoiseOnStartup")
        self.verticalLayout.addWidget(self.checkBox_LoadNoiseOnStartup)
        self.checkBox_LoadAnatonStartup = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_LoadAnatonStartup.setChecked(True)
        self.checkBox_LoadAnatonStartup.setObjectName("checkBox_LoadAnatonStartup")
        self.verticalLayout.addWidget(self.checkBox_LoadAnatonStartup)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 651, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(10, 30, 631, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(9, 290, 651, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(3)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(8, -1, 641, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.checkBox_CorrelateOnClick = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_CorrelateOnClick.setGeometry(QtCore.QRect(0, 50, 651, 21))
        self.checkBox_CorrelateOnClick.setChecked(True)
        self.checkBox_CorrelateOnClick.setObjectName("checkBox_CorrelateOnClick")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(10, 20, 631, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(9, 400, 651, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 651, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setGeometry(QtCore.QRect(10, 20, 631, 20))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.checkBox_SaveDisplayOptionsOnExit = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_SaveDisplayOptionsOnExit.setGeometry(QtCore.QRect(0, 40, 639, 21))
        self.checkBox_SaveDisplayOptionsOnExit.setObjectName("checkBox_SaveDisplayOptionsOnExit")
        self.frame_2.raise_()
        self.buttonBox.raise_()
        self.frame.raise_()
        self.frame_3.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferrences"))
        self.checkBox_LoadICAonStartup.setText(_translate("Dialog", "Load default ICA components on startup"))
        self.checkBox_LoadICNonStartup.setText(_translate("Dialog", "Load default ICN templates on startup"))
        self.checkBox_LoadNoiseOnStartup.setText(_translate("Dialog", "Load default Noise templates on startup"))
        self.checkBox_LoadAnatonStartup.setText(_translate("Dialog", "Load default anatomical/structure MRI on startup"))
        self.label.setText(_translate("Dialog", "To change default file(s) for the following, check (or uncheck & re-check) any of the following items:"))
        self.label_2.setText(_translate("Dialog", "By default, new pairs of items are correlated when clicked on.  Turning off this option may speed up GUI:"))
        self.checkBox_CorrelateOnClick.setText(_translate("Dialog", "Correlate ICA comp. && ICN template pairs when clicked"))
        self.label_4.setText(_translate("Dialog", "Display menu offers options to change plotting settings.  Use current settings as default on startup:"))
        self.checkBox_SaveDisplayOptionsOnExit.setText(_translate("Dialog", "Save current Display menu settings as default"))

