# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoo_TutorialWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StepByStepTutorial(object):
    def setupUi(self, StepByStepTutorial):
        StepByStepTutorial.setObjectName("StepByStepTutorial")
        StepByStepTutorial.resize(614, 785)
        self.buttonBox = QtWidgets.QDialogButtonBox(StepByStepTutorial)
        self.buttonBox.setGeometry(QtCore.QRect(10, 740, 591, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(StepByStepTutorial)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 59, 22, 671))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.checkBox_ICsLoaded = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_ICsLoaded.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ICsLoaded.sizePolicy().hasHeightForWidth())
        self.checkBox_ICsLoaded.setSizePolicy(sizePolicy)
        self.checkBox_ICsLoaded.setText("")
        self.checkBox_ICsLoaded.setObjectName("checkBox_ICsLoaded")
        self.verticalLayout2.addWidget(self.checkBox_ICsLoaded)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout2.addItem(spacerItem)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout2.addWidget(self.line_4)
        self.checkBox_ICNsLoaded = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_ICNsLoaded.setEnabled(False)
        self.checkBox_ICNsLoaded.setText("")
        self.checkBox_ICNsLoaded.setObjectName("checkBox_ICNsLoaded")
        self.verticalLayout2.addWidget(self.checkBox_ICNsLoaded)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout2.addItem(spacerItem1)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout2.addWidget(self.line_5)
        self.checkBox_ClassificationsPresent = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_ClassificationsPresent.setEnabled(False)
        self.checkBox_ClassificationsPresent.setText("")
        self.checkBox_ClassificationsPresent.setObjectName("checkBox_ClassificationsPresent")
        self.verticalLayout2.addWidget(self.checkBox_ClassificationsPresent)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout2.addItem(spacerItem2)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout2.addWidget(self.line_6)
        self.checkBox_OutputGenerated = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_OutputGenerated.setEnabled(False)
        self.checkBox_OutputGenerated.setText("")
        self.checkBox_OutputGenerated.setObjectName("checkBox_OutputGenerated")
        self.verticalLayout2.addWidget(self.checkBox_OutputGenerated)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout2.addItem(spacerItem3)
        self.title_ = QtWidgets.QLabel(StepByStepTutorial)
        self.title_.setGeometry(QtCore.QRect(10, 10, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_.setFont(font)
        self.title_.setAlignment(QtCore.Qt.AlignCenter)
        self.title_.setObjectName("title_")
        self.verticalLayoutWidget = QtWidgets.QWidget(StepByStepTutorial)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(39, 59, 738, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_ICAstep_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ICAstep_title.setFont(font)
        self.label_ICAstep_title.setObjectName("label_ICAstep_title")
        self.verticalLayout_5.addWidget(self.label_ICAstep_title)
        self.label_ICAstep_details = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ICAstep_details.setFont(font)
        self.label_ICAstep_details.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_ICAstep_details.setWordWrap(True)
        self.label_ICAstep_details.setIndent(-1)
        self.label_ICAstep_details.setObjectName("label_ICAstep_details")
        self.verticalLayout_5.addWidget(self.label_ICAstep_details)
        self.verticalLayout_5.setStretch(1, 10)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_ICNstep_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ICNstep_title.setFont(font)
        self.label_ICNstep_title.setObjectName("label_ICNstep_title")
        self.verticalLayout_4.addWidget(self.label_ICNstep_title)
        self.label_ICNstep_details = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ICNstep_details.setFont(font)
        self.label_ICNstep_details.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_ICNstep_details.setWordWrap(True)
        self.label_ICNstep_details.setObjectName("label_ICNstep_details")
        self.verticalLayout_4.addWidget(self.label_ICNstep_details)
        self.verticalLayout_4.setStretch(1, 10)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Mapstep_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Mapstep_title.setFont(font)
        self.label_Mapstep_title.setObjectName("label_Mapstep_title")
        self.verticalLayout_2.addWidget(self.label_Mapstep_title)
        self.label_Mapstep_details = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Mapstep_details.setFont(font)
        self.label_Mapstep_details.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Mapstep_details.setWordWrap(True)
        self.label_Mapstep_details.setObjectName("label_Mapstep_details")
        self.verticalLayout_2.addWidget(self.label_Mapstep_details)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Output_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Output_title.setFont(font)
        self.label_Output_title.setObjectName("label_Output_title")
        self.verticalLayout_3.addWidget(self.label_Output_title)
        self.label_OUtput_details = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_OUtput_details.setFont(font)
        self.label_OUtput_details.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_OUtput_details.setWordWrap(True)
        self.label_OUtput_details.setObjectName("label_OUtput_details")
        self.verticalLayout_3.addWidget(self.label_OUtput_details)
        self.verticalLayout_3.setStretch(1, 10)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.line_7 = QtWidgets.QFrame(StepByStepTutorial)
        self.line_7.setGeometry(QtCore.QRect(10, 40, 591, 20))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")

        self.retranslateUi(StepByStepTutorial)
        self.buttonBox.accepted.connect(StepByStepTutorial.accept)
        self.buttonBox.rejected.connect(StepByStepTutorial.reject)
        QtCore.QMetaObject.connectSlotsByName(StepByStepTutorial)

    def retranslateUi(self, StepByStepTutorial):
        _translate = QtCore.QCoreApplication.translate
        StepByStepTutorial.setWindowTitle(_translate("StepByStepTutorial", "Step-by-Step tutorial & tips"))
        self.title_.setText(_translate("StepByStepTutorial", "Analysis: Steps Completed & Suggestions"))
        self.label_ICAstep_title.setText(_translate("StepByStepTutorial", "1. Load ICA components"))
        self.label_ICAstep_details.setText(_translate("StepByStepTutorial", "-click \"Load ICA components\" button or select from \"Networks\" menu"))
        self.label_ICNstep_title.setText(_translate("StepByStepTutorial", "2. Load ICN templates"))
        self.label_ICNstep_details.setText(_translate("StepByStepTutorial", "-click \"Load ICN templates\" button or select from \"Networks\" menu"))
        self.label_Mapstep_title.setText(_translate("StepByStepTutorial", "3. Select mappings/classifications"))
        self.label_Mapstep_details.setText(_translate("StepByStepTutorial", "<html><head/><body><p>-select an ICA comp. &amp; ICN from respective lists...</p><p>-...then click on &quot;Set Classification (ICA &gt; ICN)&quot; button</p></body></html>"))
        self.label_Output_title.setText(_translate("StepByStepTutorial", "4. Create figures, tables and masks"))
        self.label_OUtput_details.setText(_translate("StepByStepTutorial", "<html><head/><body><p>-create ICA &gt; ICN mapping(s) in step 3.</p><p>-click on &quot;Create Output Figure(s) and Table&quot;</p><p>-select &quot;Create masks from classifications&quot; from &quot;Masks&quot; menu</p></body></html>"))

