# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoo_DisplayOptionsWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(661, 734)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 670, 591, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(170, 400, 301, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 301, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_DisplayICAtime = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DisplayICAtime.setFont(font)
        self.checkBox_DisplayICAtime.setObjectName("checkBox_DisplayICAtime")
        self.verticalLayout.addWidget(self.checkBox_DisplayICAtime)
        self.checkBox_DisplayICAfreq = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_DisplayICAfreq.setFont(font)
        self.checkBox_DisplayICAfreq.setObjectName("checkBox_DisplayICAfreq")
        self.verticalLayout.addWidget(self.checkBox_DisplayICAfreq)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ChangeTR = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ChangeTR.setFont(font)
        self.pushButton_ChangeTR.setObjectName("pushButton_ChangeTR")
        self.horizontalLayout.addWidget(self.pushButton_ChangeTR)
        self.label_currentTR = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_currentTR.setFont(font)
        self.label_currentTR.setObjectName("label_currentTR")
        self.horizontalLayout.addWidget(self.label_currentTR)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 210, 301, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, 19, 301, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_ShowICNtemplate = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ShowICNtemplate.setFont(font)
        self.checkBox_ShowICNtemplate.setChecked(True)
        self.checkBox_ShowICNtemplate.setObjectName("checkBox_ShowICNtemplate")
        self.verticalLayout_2.addWidget(self.checkBox_ShowICNtemplate)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_ThreshICAvol = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ThreshICAvol.setFont(font)
        self.pushButton_ThreshICAvol.setObjectName("pushButton_ThreshICAvol")
        self.horizontalLayout_2.addWidget(self.pushButton_ThreshICAvol)
        self.label_currentICAvolThresh = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_currentICAvolThresh.setFont(font)
        self.label_currentICAvolThresh.setObjectName("label_currentICAvolThresh")
        self.horizontalLayout_2.addWidget(self.label_currentICAvolThresh)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_ChangeAnatomicalvol = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ChangeAnatomicalvol.setFont(font)
        self.pushButton_ChangeAnatomicalvol.setObjectName("pushButton_ChangeAnatomicalvol")
        self.horizontalLayout_3.addWidget(self.pushButton_ChangeAnatomicalvol)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_CurrentAnatomicalName = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_CurrentAnatomicalName.setFont(font)
        self.label_CurrentAnatomicalName.setObjectName("label_CurrentAnatomicalName")
        self.horizontalLayout_6.addWidget(self.label_CurrentAnatomicalName)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 301, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(-1, 19, 241, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_ShowMappingName = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ShowMappingName.setFont(font)
        self.checkBox_ShowMappingName.setChecked(True)
        self.checkBox_ShowMappingName.setObjectName("checkBox_ShowMappingName")
        self.verticalLayout_5.addWidget(self.checkBox_ShowMappingName)
        self.checkBox_ShowICAName = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ShowICAName.setFont(font)
        self.checkBox_ShowICAName.setChecked(True)
        self.checkBox_ShowICAName.setObjectName("checkBox_ShowICAName")
        self.verticalLayout_5.addWidget(self.checkBox_ShowICAName)
        self.checkBox_ShowICNName = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ShowICNName.setFont(font)
        self.checkBox_ShowICNName.setChecked(True)
        self.checkBox_ShowICNName.setObjectName("checkBox_ShowICNName")
        self.verticalLayout_5.addWidget(self.checkBox_ShowICNName)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_ChangeTextSize = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ChangeTextSize.setFont(font)
        self.pushButton_ChangeTextSize.setObjectName("pushButton_ChangeTextSize")
        self.horizontalLayout_4.addWidget(self.pushButton_ChangeTextSize)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 10, 291, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, 19, 291, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_SliceLayoutMatrix = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SliceLayoutMatrix.setFont(font)
        self.checkBox_SliceLayoutMatrix.setObjectName("checkBox_SliceLayoutMatrix")
        self.verticalLayout_3.addWidget(self.checkBox_SliceLayoutMatrix)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_numRows = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_numRows.setEnabled(False)
        self.spinBox_numRows.setMinimum(1)
        self.spinBox_numRows.setMaximum(49)
        self.spinBox_numRows.setObjectName("spinBox_numRows")
        self.gridLayout.addWidget(self.spinBox_numRows, 1, 0, 1, 1)
        self.spinBox_numCols = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_numCols.setEnabled(False)
        self.spinBox_numCols.setMinimum(1)
        self.spinBox_numCols.setMaximum(50)
        self.spinBox_numCols.setProperty("value", 5)
        self.spinBox_numCols.setObjectName("spinBox_numCols")
        self.gridLayout.addWidget(self.spinBox_numCols, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.checkBox_ShowCrosshairs = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ShowCrosshairs.setFont(font)
        self.checkBox_ShowCrosshairs.setChecked(True)
        self.checkBox_ShowCrosshairs.setObjectName("checkBox_ShowCrosshairs")
        self.verticalLayout_3.addWidget(self.checkBox_ShowCrosshairs)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 570, 611, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_SaveDisplayOptions = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_SaveDisplayOptions.setGeometry(QtCore.QRect(10, 40, 151, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_SaveDisplayOptions.setFont(font)
        self.pushButton_SaveDisplayOptions.setObjectName("pushButton_SaveDisplayOptions")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(178, 24, 431, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Display Options"))
        self.groupBox.setTitle(_translate("Dialog", "Time/frequency plotting options:"))
        self.checkBox_DisplayICAtime.setText(_translate("Dialog", "Display ICA time series"))
        self.checkBox_DisplayICAfreq.setText(_translate("Dialog", "Display ICA freq. spectrum"))
        self.pushButton_ChangeTR.setText(_translate("Dialog", "Change TR"))
        self.label_currentTR.setText(_translate("Dialog", "(current TR)"))
        self.groupBox_2.setTitle(_translate("Dialog", "MRI/fMRI volume plotting options:"))
        self.checkBox_ShowICNtemplate.setText(_translate("Dialog", "Show ICN template vol."))
        self.pushButton_ThreshICAvol.setText(_translate("Dialog", "Threshold ICA vol."))
        self.label_currentICAvolThresh.setText(_translate("Dialog", "(% percentile)"))
        self.pushButton_ChangeAnatomicalvol.setText(_translate("Dialog", "Change sMRI vol."))
        self.label_CurrentAnatomicalName.setText(_translate("Dialog", "(current sMRI) "))
        self.groupBox_3.setTitle(_translate("Dialog", "Text display options:"))
        self.checkBox_ShowMappingName.setText(_translate("Dialog", "Show classification name"))
        self.checkBox_ShowICAName.setText(_translate("Dialog", "Show ICA component name"))
        self.checkBox_ShowICNName.setText(_translate("Dialog", "Show ICN template name"))
        self.pushButton_ChangeTextSize.setText(_translate("Dialog", "Change Text Size"))
        self.groupBox_4.setTitle(_translate("Dialog", "Misc. other plotting options:"))
        self.checkBox_SliceLayoutMatrix.setText(_translate("Dialog", "Layout slices in rectangular grid"))
        self.label_2.setText(_translate("Dialog", "Number of columns:"))
        self.label_3.setText(_translate("Dialog", "Number of rows:"))
        self.checkBox_ShowCrosshairs.setText(_translate("Dialog", "Show crosshairs"))
        self.groupBox_5.setTitle(_translate("Dialog", "Save current display settings as Network Zoo defaults:"))
        self.pushButton_SaveDisplayOptions.setText(_translate("Dialog", "Save display options"))
        self.label.setText(_translate("Dialog", "By default, current display settings are discarded once Network Zoo closes. Saving current display will set these options as the default for future use"))

