# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoo_OutputOptionsWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(667, 414)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 350, 641, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 641, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 451, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_ThreshICApercentile = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ThreshICApercentile.setFont(font)
        self.checkBox_ThreshICApercentile.setChecked(True)
        self.checkBox_ThreshICApercentile.setObjectName("checkBox_ThreshICApercentile")
        self.horizontalLayout.addWidget(self.checkBox_ThreshICApercentile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setMaximum(100.0)
        self.doubleSpinBox.setSingleStep(0.5)
        self.doubleSpinBox.setProperty("value", 99.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_ThreshICAfractionOfMax = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_ThreshICAfractionOfMax.setFont(font)
        self.checkBox_ThreshICAfractionOfMax.setChecked(True)
        self.checkBox_ThreshICAfractionOfMax.setObjectName("checkBox_ThreshICAfractionOfMax")
        self.horizontalLayout_3.addWidget(self.checkBox_ThreshICAfractionOfMax)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setSingleStep(0.03)
        self.doubleSpinBox_2.setProperty("value", 0.33)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.checkBox_SmoothEdges = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_SmoothEdges.setFont(font)
        self.checkBox_SmoothEdges.setChecked(True)
        self.checkBox_SmoothEdges.setObjectName("checkBox_SmoothEdges")
        self.verticalLayout.addWidget(self.checkBox_SmoothEdges)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(498, 29, 131, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 220, 641, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_SaveOutputOptions = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_SaveOutputOptions.setGeometry(QtCore.QRect(10, 30, 151, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_SaveOutputOptions.setFont(font)
        self.pushButton_SaveOutputOptions.setObjectName("pushButton_SaveOutputOptions")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(178, 24, 441, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Output Options"))
        self.groupBox.setTitle(_translate("Dialog", "Mask creation options:"))
        self.checkBox_ThreshICApercentile.setText(_translate("Dialog", "Threshold ICA vol. by percentile:"))
        self.checkBox_ThreshICAfractionOfMax.setText(_translate("Dialog", "Threshold ICA vol. by fraction of |max value|:"))
        self.checkBox_SmoothEdges.setText(_translate("Dialog", "Smooth edges of mask"))
        self.label.setText(_translate("Dialog", "Masks are created by thresholding classified ICA comp. vols., then labelled with the ICN template name"))
        self.groupBox_5.setTitle(_translate("Dialog", "Save current output creation settings as Network Zoo defaults:"))
        self.pushButton_SaveOutputOptions.setText(_translate("Dialog", "Save output settings"))
        self.label_2.setText(_translate("Dialog", "By default, current output creation settings are discarded once Network Zoo closes. Saving current settings will set these options as the default for future use"))

